[build]
  publish = "site"
  command = "mkdocs build"

[build.environment]
  PYTHON_VERSION = "3.8"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[[redirects]]
  from = "/architecture/*"
  to = "/1.3/architecture/:splat"
  status = 301

[[redirects]]
  from = "/getting-started/*"
  to = "/1.3/getting-started/:splat"
  status = 301

[[redirects]]
  from = "/monitoring/*"
  to = "/1.3/monitoring/:splat"
  status = 301

[[redirects]]
  from = "/tutorial/*"
  to = "/1.3/tutorial/:splat"
  status = 301

[[redirects]]
  from = "/user-guide/*"
  to = "/1.3/user-guide/:splat"
  status = 301

[[redirects]]
  from = "/changelog/*"
  to = "/1.3/changelog/:splat"
  status = 301


[context.production.environment]
  MKDOCS_ENV = "production"

[context.deploy-preview.environment]
  MKDOCS_ENV = "preview"

# Use Netlify's built-in caching
[build.processing]
  skip_processing = false
[build.processing.css]
  bundle = true
  minify = true
[build.processing.js]
  bundle = true
  minify = true
[build.processing.html]
  pretty_urls = true
[build.processing.images]
  compress = true
